version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
    versions:
    - 4.2.2
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: io.projectreactor:reactor-test
    versions:
    - 3.4.2
    - 3.4.3
    - 3.4.4
  - dependency-name: com.esotericsoftware:kryo
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
